author:
  name: narlock
description: Alder - narlock's Discord bot companion that provides focus, productivity, statistics, and leisure features.
baseurl: ""

# Build settings
remote_theme: jekyll/minima@1e8a445
minima:
  skin: dark
  social_links:
    - title: GitHub profile
      icon: github
      url: "https://github.com/narlock"
    - title: narlockdev on X (formerly Twitter)
      icon: x-twitter
      url: "https://twitter.com/narlockdev"
    - title: narlock on YouTube
      icon: youtube
      url: "https://youtube.com/@narlock"

header_pages:
  - install.markdown
  # - tutorial.markdown
  - features.markdown
  # - documentation.markdown
